#!/usr/bin/env ruby
#^syntax detection

forge 'https://forgeapi.puppetlabs.com'

mod 'stahnma-epel'

mod 'datacentred-ldap',
    :git => 'https://github.com/Puppet-Finland/datacentred-ldap.git'

mod 'puppetfinland-monit',
    :git => 'https://github.com/Puppet-Finland/monit.git'

mod 'puppetfinland-os',
    :git => 'https://github.com/Puppet-Finland/os.git'

mod 'puppetfinland-packetfilter',
    :git => 'https://github.com/Puppet-Finland/packetfilter.git'

mod 'puppetfinland-ruby',
    :git => 'https://github.com/Puppet-Finland/puppet-ruby.git',
    :tag => '0.3.3'

mod 'puppetlabs-stdlib'

mod 'puppetfinland-systemd',
    :git => 'https://github.com/Puppet-Finland/puppet-systemd.git'

mod 'puppetfinland-tomcat',
    :git => 'https://github.com/Puppet-Finland/puppet-module-tomcat.git'
